server:
  port: 8005
spring:
  application:
    name: time-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/workforce
    username: workforce
    password: workforce
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
jwt:
  secret: workforce-super-secret-jwt-key-change-in-production-min-256-bits
